#!/bin/bash
set -o nounset -o errexit -o pipefail

##Install VSCode and requirements including Node
apt-get update -qq && \
curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
apt-get install \
  jq \
  libx11-dev \
  libxkbfile-dev \
  libsecret-1-dev \
  node-gyp \
  nodejs -y && \
pip install -q python-language-server autopep8 flake8 pylint && \
apt-get clean && \
rm -rf \
  /tmp/* \
  /var/lib/apt/lists/* \
  /var/tmp/*

CODE_SERVER_VERSION=3.9.0

mkdir -p /opt/bin/code-server && \
cd /opt/bin/code-server && \
wget -qO- https://github.com/cdr/code-server/releases/download/v$CODE_SERVER_VERSION/code-server-$CODE_SERVER_VERSION-linux-amd64.tar.gz| tar zxf - --strip-components=1 && \
echo 'export PATH=/opt/bin/code-server:$PATH' >> /home/ubuntu/.domino-defaults && \
apt-get purge --auto-remove -y \
  libx11-dev \
  libxkbfile-dev \
  libsecret-1-dev && \
apt-get clean && \
rm -rf \
  /tmp/* \
  /var/lib/apt/lists/* \
  /var/tmp/*
